Feature: User Login # features/login.feature:1

  @invalid_login
  Scenario: Unsuccessful login with invalid credentials  # features/login.feature:4
    Given the OpenFin application is launched            # steps/login_steps.py:12
    When I enter invalid credentials                     # steps/login_steps.py:27
    Then I should see an error message                   # steps/login_steps.py:71

  @valid_login
  Scenario: Successful login                  # features/login.feature:10
    Given the OpenFin application is launched # steps/login_steps.py:12
    When I enter valid credentials            # steps/login_steps.py:18
    Then I should be logged in successfully   # steps/login_steps.py:44
      Assertion Failed: Error connecting to Dock window: Dock window not found after login!
      Captured logging:
      INFO:builtins:Launching the OpenFin application...
      INFO:automation:Launching OpenFin application...
      INFO:automation:Waiting for the Mizuho login window to appear...
      INFO:automation:Found window: Mizuho Front Office
      INFO:builtins:OpenFin application launched.
      INFO:builtins:Entering valid credentials...
      INFO:automation:Filling in login credentials...
      INFO:automation:Login attempt made.
      INFO:builtins:Valid credentials entered.
      INFO:automation:Found window: [EHUB-6025] Navigation & Dock Window Interactions - Mizuho International - Google Chrome
      ERROR:builtins:Dock window not found after login!
      ERROR:builtins:Error connecting to Dock window: Dock window not found after login!


